In [1]:
1 + 2

3

In [2]:
4 * 5

20

In [3]:
5 / 6

0.8333333333333334

In [4]:
5 // 6

0

In [5]:
5.0 / 6

0.8333333333333334

In [6]:
3 + (4 + 5) * 8

75

In [7]:
print("hello world")

hello world


In [8]:
print("你好")

你好


In [9]:
print('hello')

hello


In [10]:
from math import pi

In [11]:
print(pi)

3.141592653589793


In [13]:
print("pi = %.2f" %pi)

pi = 3.14


In [20]:
a = 'Ashlee works from home.'

In [22]:
a = a.rstrip('.')
a

'Ashlee works from home'

In [23]:
a.split(' ')

['Ashlee', 'works', 'from', 'home']

In [24]:
b = [1, 2, 3, 4]

In [25]:
b[0]

1

In [26]:
b[3]

4

In [27]:
b[-1]

4

In [29]:
b[0:2]

[1, 2]

In [30]:
b[:2]

[1, 2]

In [31]:
b[2:]

[3, 4]

In [32]:
c = [[1, 2], [3, 4]]

In [33]:
c[0]

[1, 2]

In [35]:
c[0][1]

2

In [36]:
d = {}

In [37]:
type(d)

dict

In [38]:
d['bird'] = '鸟'
d['kangaroo'] = '袋鼠'
d['dog'] = '狗'

In [39]:
d

{'bird': '鸟', 'kangaroo': '袋鼠', 'dog': '狗'}

In [40]:
d['bird']

'鸟'

In [41]:
e = {}

In [42]:
e['winter'] = [0, -1, 1, 2]
e['summer'] = [35, 30, 25, 25]

In [43]:
e

{'winter': [0, -1, 1, 2], 'summer': [35, 30, 25, 25]}

In [44]:
e['winter']

[0, -1, 1, 2]

In [45]:
import numpy as np

In [47]:
f = np.array([[1, 2], [3, 4]])

In [48]:
g = [[1, 2], [3, 4]]

In [49]:
f[0][0]

1

In [50]:
f * 3

array([[ 3,  6],
       [ 9, 12]])

In [51]:
g * 3

[[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]]

In [52]:
f + f

array([[2, 4],
       [6, 8]])

In [53]:
np.mean(f)

2.5

In [58]:
# get a random number from 1 to 99
np.random.randint(1, 100)

99

In [59]:
np.mean(f, axis = 0)

array([2., 3.])

In [60]:
np.mean(f, axis = 1)

array([1.5, 3.5])